/**
 * # Defines one value of a SpeciesFeature.
 *
 * The PossibleSpeciesFeatureValue object is a child of a SpeciesFeatureType,
 * and defines one value (though its optional "numericValue" attribute) which
 * the parent SpeciesFeatureType can hold.
 */
[Prefix="libsbml"]
interface PossibleSpeciesFeatureValue {
  /**
   * Returns the value of the "numericValue" attribute of this
   * PossibleSpeciesFeatureValue.
   *
   * @return {string} the value of the "numericValue" attribute of this
   * PossibleSpeciesFeatureValue as a string.
   */
  DOMString getNumericValue();


  /**
   * Returns true if this PossibleSpeciesFeatureValue's "numericValue"
   * attribute has been set.
   *
   * @return {boolean} true if this PossibleSpeciesFeatureValue's "numericValue"
   * attribute has been set; otherwise, false is returned.
   */
  boolean isSetNumericValue();


  /**
   * Sets the value of the "numericValue" attribute of this
   * PossibleSpeciesFeatureValue.
   *
   * @param {string} numericValue the new "numericValue" attribute value.
   */
  long setNumericValue(DOMString numericValue);


  /**
   * Unsets the value of the "numericValue" attribute of this
   * PossibleSpeciesFeatureValue.
   */
  long unsetNumericValue();
};

PossibleSpeciesFeatureValue implements SBase;
