/**
 * # AnalyticVolume class
 */
[Prefix="libsbml::"]
interface AnalyticVolume {
  /**
   * Returns the value of the "value" attribute of this Boundary.
   *
   * @return {number} the value of the "value" attribute of this Boundary as a double.
   */
  double getValue();


  /**
   * Predicate returning true if this Boundary's "value" attribute is set.
   *
   * return {boolean} true if this Boundary's "value" attribute has been set,
   * otherwise false is returned.
   */
  boolean isSetValue();


  /**
   * Sets the value of the "value" attribute of this Boundary.
   *
   * @param {number} value double value of the "value" attribute to be set.
   */
  long setValue(double value);


  /**
   * Unsets the value of the "value" attribute of this Boundary.
   */
  long unsetValue();
};

AnalyticVolume implements SBase;