/**
 * SBMLSpatialTypeCode_t Enumeration of possible types in the libSBML
 * "spatial" package implementation.
 */
enum libsbml__idl__SBMLSpatialTypeCode_t {
  "libsbml::SBML_SPATIAL_DOMAINTYPE",
  "libsbml::SBML_SPATIAL_DOMAIN",
  "libsbml::SBML_SPATIAL_INTERIORPOINT",
  "libsbml::SBML_SPATIAL_BOUNDARY",
  "libsbml::SBML_SPATIAL_ADJACENTDOMAINS",
  "libsbml::SBML_SPATIAL_GEOMETRYDEFINITION",
  "libsbml::SBML_SPATIAL_COMPARTMENTMAPPING",
  "libsbml::SBML_SPATIAL_COORDINATECOMPONENT",
  "libsbml::SBML_SPATIAL_SAMPLEDFIELDGEOMETRY",
  "libsbml::SBML_SPATIAL_SAMPLEDFIELD",
  "libsbml::SBML_SPATIAL_SAMPLEDVOLUME",
  "libsbml::SBML_SPATIAL_ANALYTICGEOMETRY",
  "libsbml::SBML_SPATIAL_ANALYTICVOLUME",
  "libsbml::SBML_SPATIAL_PARAMETRICGEOMETRY",
  "libsbml::SBML_SPATIAL_PARAMETRICOBJECT",
  "libsbml::SBML_SPATIAL_CSGEOMETRY",
  "libsbml::SBML_SPATIAL_CSGOBJECT",
  "libsbml::SBML_SPATIAL_CSGNODE",
  "libsbml::SBML_SPATIAL_CSGTRANSFORMATION",
  "libsbml::SBML_SPATIAL_CSGTRANSLATION",
  "libsbml::SBML_SPATIAL_CSGROTATION",
  "libsbml::SBML_SPATIAL_CSGSCALE",
  "libsbml::SBML_SPATIAL_CSGHOMOGENEOUSTRANSFORMATION",
  "libsbml::SBML_SPATIAL_TRANSFORMATIONCOMPONENT",
  "libsbml::SBML_SPATIAL_CSGPRIMITIVE",
  "libsbml::SBML_SPATIAL_CSGSETOPERATOR",
  "libsbml::SBML_SPATIAL_SPATIALSYMBOLREFERENCE",
  "libsbml::SBML_SPATIAL_DIFFUSIONCOEFFICIENT",
  "libsbml::SBML_SPATIAL_ADVECTIONCOEFFICIENT",
  "libsbml::SBML_SPATIAL_BOUNDARYCONDITION",
  "libsbml::SBML_SPATIAL_GEOMETRY",
  "libsbml::SBML_SPATIAL_MIXEDGEOMETRY",
  "libsbml::SBML_SPATIAL_ORDINALMAPPING",
  "libsbml::SBML_SPATIAL_SPATIALPOINTS"
};

/**
 * Enumeration of values permitted as the value of the "boundarykind"
 * attribute on Spatial objects.
 */
enum libsbml__idl__BoundaryConditionKind_t {
  "libsbml::SPATIAL_BOUNDARYKIND_ROBIN_VALUE_COEFFICIENT",
  "libsbml::SPATIAL_BOUNDARYKIND_ROBIN_INWARD_NORMAL_GRADIENT_COEFFICIENT",
  "libsbml::SPATIAL_BOUNDARYKIND_ROBIN_SUM",
  "libsbml::SPATIAL_BOUNDARYKIND_NEUMANN",
  "libsbml::SPATIAL_BOUNDARYKIND_DIRICHLET",
  "libsbml::SPATIAL_BOUNDARYKIND_INVALID"
};


/**
 * Enumeration of values permitted as the value of the "compressionkind"
 * attribute on Spatial objects.
 */
enum libsbml__idl__CompressionKind_t {
  "libsbml::SPATIAL_COMPRESSIONKIND_UNCOMPRESSED",
  "libsbml::SPATIAL_COMPRESSIONKIND_DEFLATED",
  "libsbml::SPATIAL_COMPRESSIONKIND_INVALID"
};

/**
 * Enumeration of values permitted as the value of the "datakind"
 * attribute on Spatial objects.
 */
enum libsbml__idl__DataKind_t {
  "libsbml::SPATIAL_DATAKIND_DOUBLE",
  "libsbml::SPATIAL_DATAKIND_FLOAT",
  "libsbml::SPATIAL_DATAKIND_UINT8",
  "libsbml::SPATIAL_DATAKIND_UINT16",
  "libsbml::SPATIAL_DATAKIND_UINT32",
  "libsbml::SPATIAL_DATAKIND_INVALID"
};

/**
 * # Implementation of the SpatialExtension class
 */
[Prefix="libsbml::"]
interface SpatialExtension {
  /**
   * Returns the XML namespace URI of the SBML Level 3 package implemented
   * by this libSBML extension.
   *
   * @return {string} the XML namespaceas a string.
   */
  static DOMString getXmlnsL3V1V1();
};

/**
 * Enumeration of values permitted as the value of the "coordinatekind"
 * attribute on Spatial objects.
 */
enum libsbml__idl__CoordinateKind_t {
  "libsbml::SPATIAL_COORDINATEKIND_CARTESIAN_X",
  "libsbml::SPATIAL_COORDINATEKIND_CARTESIAN_Y",
  "libsbml::SPATIAL_COORDINATEKIND_CARTESIAN_Z",
  "libsbml::SPATIAL_COORDINATEKIND_INVALID"
};

/**
 * Enumeration of values permitted as the value of the "functionkind"
 * attribute on Spatial objects.
 */
enum FunctionKind_t{
  "libsbml::SPATIAL_FUNCTIONKIND_LAYERED",
  "libsbml::SPATIAL_FUNCTIONKIND_INVALID"
};

/**
 * Enumeration of values permitted as the value of the "primitivekind"
 * attribute on Spatial objects.
 */
enum PrimitiveKind_t {
  "libsbml::SPATIAL_PRIMITIVEKIND_SPHERE",
  "libsbml::SPATIAL_PRIMITIVEKIND_CUBE",
  "libsbml::SPATIAL_PRIMITIVEKIND_CYLINDER",
  "libsbml::SPATIAL_PRIMITIVEKIND_CONE",
  "libsbml::SPATIAL_PRIMITIVEKIND_CIRCLE",
  "libsbml::SPATIAL_PRIMITIVEKIND_SQUARE",
  "libsbml::SPATIAL_PRIMITIVEKIND_RIGHTTRIANGLE",
  "libsbml::SPATIAL_PRIMITIVEKIND_INVALID"
};

/**
 * Enumeration of values permitted as the value of the "diffusionkind"
 * attribute on Spatial objects.
 */
enum DiffusionKind_t {
  "libsbml::SPATIAL_DIFFUSIONKIND_ISOTROPIC",
  "libsbml::SPATIAL_DIFFUSIONKIND_ANISOTROPIC",
  "libsbml::SPATIAL_DIFFUSIONKIND_TENSOR",
  "libsbml::SPATIAL_DIFFUSIONKIND_INVALID"
};

/**
 * Enumeration of values permitted as the value of the "geometrykind"
 * attribute on Spatial objects.
 */
enum GeometryKind_t {
  "libsbml::SPATIAL_GEOMETRYKIND_CARTESIAN",
  "libsbml::SPATIAL_GEOMETRYKIND_INVALID"
};

/**
 * Enumeration of values permitted as the value of the "setoperation"
 * attribute on Spatial objects.
 */
enum SetOperation_t {
  "libsbml::SPATIAL_SETOPERATION_UNION",
  "libsbml::SPATIAL_SETOPERATION_INTERSECTION",
  "libsbml::SPATIAL_SETOPERATION_DIFFERENCE",
  "libsbml::SPATIAL_SETOPERATION_INVALID"
};

/**
 * Enumeration of values permitted as the value of the
 * "interpolationkind" attribute on Spatial objects.
 */
enum InterpolationKind_t {
  "libsbml::SPATIAL_INTERPOLATIONKIND_NEARESTNEIGHBOR",
  "libsbml::SPATIAL_INTERPOLATIONKIND_LINEAR",
  "libsbml::SPATIAL_INTERPOLATIONKIND_INVALID"
};

/**
 * Enumeration of values permitted as the value of the "polygonkind"
 * attribute on Spatial objects.
 */
enum PolygonKind_t {
  "libsbml::SPATIAL_POLYGONKIND_TRIANGLE",
  "libsbml::SPATIAL_POLYGONKIND_QUADRILATERAL",
  "libsbml::SPATIAL_POLYGONKIND_INVALID"
};
