/**
 * # SampledField class
 */
[Prefix="libsbml::"]
interface SampledField {
  /**
   * Returns the value of the "dataType" attribute of this SampledField.
   *
   * @return {DataKind_t} the value of the "dataType" attribute of this SampledField as a
   * DataKind_t.
   */
  libsbml__idl__DataKind_t getDataType();


  /**
   * Returns the value of the "dataType" attribute of this SampledField.
   *
   * @return {string} the value of the "dataType" attribute of this SampledField as a
   * string.
   */
  DOMString getDataTypeAsString();


  /**
   * Returns the value of the "numSamples1" attribute of this SampledField.
   *
   * @return {number} the value of the "numSamples1" attribute of this SampledField as a
   * integer.
   */
  long getNumSamples1();


  /**
   * Returns the value of the "numSamples2" attribute of this SampledField.
   *
   * @return {number} the value of the "numSamples2" attribute of this SampledField as a
   * integer.
   */
  long getNumSamples2();


  /**
   * Returns the value of the "numSamples3" attribute of this SampledField.
   *
   * @return {number} the value of the "numSamples3" attribute of this SampledField as a
   * integer.
   */
  long getNumSamples3();


  /**
   * Returns the value of the "interpolationType" attribute of this
   * SampledField.
   *
   * @return {InterpolationKind_t} the value of the "interpolationType" attribute of this
   * SampledField as a InterpolationKind_t.
   */
  libsbml__idl__InterpolationKind_t getInterpolationType();


  /**
   * Returns the value of the "interpolationType" attribute of this
   * SampledField.
   *
   * @return {string} the value of the "interpolationType" attribute of this
   * SampledField as a string.
   */
  DOMString getInterpolationTypeAsString();


  /**
   * Returns the value of the "compression" attribute of this SampledField.
   *
   * @return {CompressionKind_t} the value of the "compression" attribute of this SampledField as a
   * CompressionKind_t.
   */
  CompressionKind_t getCompression();


  /**
   * Returns the value of the "compression" attribute of this SampledField.
   *
   * @return {string} the value of the "compression" attribute of this SampledField as a
   * string.
   */
  DOMString getCompressionAsString();
  //bgoli22


  /**
   * Returns the value of the "samples" attribute of this SampledField.
   *
   * @param outArray long* array that will be used to return the value of the
   * "samples" attribute of this SampledField.
   *
   * **Note:** the value of the "samples" attribute of this SampledField is
   * returned in the argument array.
   */
  void getSamples(long[] outArray);


  /**
   * Returns the value of the "samplesLength" attribute of this SampledField.
   *
   * @return {number} the value of the "samplesLength" attribute of this SampledField as
   * a integer.
   */
  long getSamplesLength();


  /**
   * Predicate returning true if this SampledField's "dataType" attribute is
   * set.
   *
   * return {boolean} true if this SampledField's "dataType" attribute has been set,
   * otherwise false is returned.
   */
  boolean isSetDataType();


  /**
   * Predicate returning true if this SampledField's "numSamples1" attribute
   * is set.
   *
   * return {boolean} true if this SampledField's "numSamples1" attribute has been
   * set, otherwise false is returned.
   */
  boolean isSetNumSamples1();


  /**
   * Predicate returning true if this SampledField's "numSamples2" attribute
   * is set.
   *
   * return {boolean} true if this SampledField's "numSamples2" attribute has been
   * set, otherwise false is returned.
   */
  boolean isSetNumSamples2();


  /**
   * Predicate returning true if this SampledField's "numSamples3" attribute
   * is set.
   *
   * return {boolean} true if this SampledField's "numSamples3" attribute has been
   * set, otherwise false is returned.
   */
  boolean isSetNumSamples3();


  /**
   * Predicate returning true if this SampledField's "interpolationType"
   * attribute is set.
   *
   * return {boolean} true if this SampledField's "interpolationType" attribute has
   * been set, otherwise false is returned.
   */
  boolean isSetInterpolationType();


  /**
   * Predicate returning true if this SampledField's "compression" attribute
   * is set.
   *
   * return {boolean} true if this SampledField's "compression" attribute has been
   * set, otherwise false is returned.
   */
  boolean isSetCompression();


  /**
   * Predicate returning true if this SampledField's "samples" attribute is
   * set.
   *
   * return {boolean} true if this SampledField's "samples" attribute has been set,
   * otherwise false is returned.
   */
  boolean isSetSamples();


  /**
   * Predicate returning true if this SampledField's "samplesLength"
   * attribute is set.
   *
   * return {boolean} true if this SampledField's "samplesLength" attribute has been
   * set, otherwise false is returned.
   */
  boolean isSetSamplesLength();


  /**
   * Sets the value of the "dataType" attribute of this SampledField.
   *
   * @param {DataKind_t} dataType DataKind_t value of the "dataType" attribute to be set.
   */
  long setDataType(libsbml__idl__DataKind_t dataType);


  /**
   * Sets the value of the "dataType" attribute of this SampledField.
   *
   * @param {string} dataType DOMString& of the "dataType" attribute to be set.
   */
  /*long setDataType(DOMString dataType);*/


  /**
   * Sets the value of the "numSamples1" attribute of this SampledField.
   *
   * @param {number} numSamples1 long value of the "numSamples1" attribute to be set.
   */
  long setNumSamples1(long numSamples1);


  /**
   * Sets the value of the "numSamples2" attribute of this SampledField.
   *
   * @param {number} numSamples2 long value of the "numSamples2" attribute to be set.
   */
  long setNumSamples2(long numSamples2);


  /**
   * Sets the value of the "numSamples3" attribute of this SampledField.
   *
   * @param {number} numSamples3 long value of the "numSamples3" attribute to be set.
   */
  long setNumSamples3(long numSamples3);


  /**
   * Sets the value of the "interpolationType" attribute of this SampledField.
   *
   * @param {InterpolationKind_t} interpolationType InterpolationKind_t value of the
   * "interpolationType" attribute to be set.
   */
  long setInterpolationType(libsbml__idl__InterpolationKind_t interpolationType);


  /**
   * Sets the value of the "compression" attribute of this SampledField.
   *
   * @param {CompressionKind_t} compression CompressionKind_t value of the "compression" attribute
   * to be set.
   */
  long setCompression(libsbml__idl__CompressionKind_t compression);


  /**
   * Sets the value of the "samples" attribute of this SampledField.
   *
   * @param inArray long* array value of the "samples" attribute to be set.
   *
   * @param arrayLength long value for the length of the "samples" attribute to
   * be set.
   */
  long setSamples(long[] inArray, long arrayLength);


  /**
   * Sets the value of the "samplesLength" attribute of this SampledField.
   *
   * @param {number} samplesLength long value of the "samplesLength" attribute to be set.
   */
  long setSamplesLength(long samplesLength);


  /**
   * Unsets the value of the "dataType" attribute of this SampledField.
   */
  long unsetDataType();


  /**
   * Unsets the value of the "numSamples1" attribute of this SampledField.
   */
  long unsetNumSamples1();


  /**
   * Unsets the value of the "numSamples2" attribute of this SampledField.
   */
  long unsetNumSamples2();


  /**
   * Unsets the value of the "numSamples3" attribute of this SampledField.
   */
  long unsetNumSamples3();


  /**
   * Unsets the value of the "interpolationType" attribute of this
   * SampledField.
   */
  long unsetInterpolationType();


  /**
   * Unsets the value of the "compression" attribute of this SampledField.
   */
  long unsetCompression();


  /**
   * Unsets the value of the "samples" attribute of this SampledField.
   */
  long unsetSamples();


  /**
   * Unsets the value of the "samplesLength" attribute of this SampledField.
   */
  long unsetSamplesLength();
};

SampledField implements SBase;
