/**
 * # Convenience class for SBase-derived classes.
 *
 * The CompBase class derives from SBase, and defines a few functions and
 * features common to all SBase-derived classes in the SBML Level 3
 * comp ("comp") package.
 */
[Prefix="libsbml::"]
interface CompBase {
};

CompBase implements SBase;
