/**
 * # UnitKind_t
 *
 * Enumeration of predefined SBML base units.
 *
 * See the [libSBML C++ docs for UnitKind_t](http://sbml.org/Software/libSBML/5.17.0/docs//cpp-api/_unit_kind_8h.html#a9597e6a39c3bb3fde6ff0073f47f1804).
 *
 */
enum libsbml__idl__UnitKind_t {
  "libsbml::UNIT_KIND_AMPERE",
  "libsbml::UNIT_KIND_AVOGADRO",
  "libsbml::UNIT_KIND_BECQUEREL",
  "libsbml::UNIT_KIND_CANDELA",
  "libsbml::UNIT_KIND_CELSIUS",
  "libsbml::UNIT_KIND_COULOMB",
  "libsbml::UNIT_KIND_DIMENSIONLESS",
  "libsbml::UNIT_KIND_FARAD",
  "libsbml::UNIT_KIND_GRAM",
  "libsbml::UNIT_KIND_GRAY",
  "libsbml::UNIT_KIND_HENRY",
  "libsbml::UNIT_KIND_HERTZ",
  "libsbml::UNIT_KIND_ITEM",
  "libsbml::UNIT_KIND_JOULE",
  "libsbml::UNIT_KIND_KATAL",
  "libsbml::UNIT_KIND_KELVIN",
  "libsbml::UNIT_KIND_KILOGRAM",
  "libsbml::UNIT_KIND_LITER",
  "libsbml::UNIT_KIND_LITRE",
  "libsbml::UNIT_KIND_LUMEN",
  "libsbml::UNIT_KIND_LUX",
  "libsbml::UNIT_KIND_METER",
  "libsbml::UNIT_KIND_METRE",
  "libsbml::UNIT_KIND_MOLE",
  "libsbml::UNIT_KIND_NEWTON",
  "libsbml::UNIT_KIND_OHM",
  "libsbml::UNIT_KIND_PASCAL",
  "libsbml::UNIT_KIND_RADIAN",
  "libsbml::UNIT_KIND_SECOND",
  "libsbml::UNIT_KIND_SIEMENS",
  "libsbml::UNIT_KIND_SIEVERT",
  "libsbml::UNIT_KIND_STERADIAN",
  "libsbml::UNIT_KIND_TESLA",
  "libsbml::UNIT_KIND_VOLT",
  "libsbml::UNIT_KIND_WATT",
  "libsbml::UNIT_KIND_WEBER",
  "libsbml::UNIT_KIND_INVALID"
};

/**
 * # A single unit referenced in an SBML **unit definition**.
 *
 * The SBML unit definition facility uses two classes of objects,
 * UnitDefinition and Unit.  The approach to defining units in SBML is
 * compositional; for example, **meter second<sup> -2</sup>** is
 * constructed by combining a Unit object representing **meter** with
 * another Unit object representing **second<sup> -2</sup>**.
 * The combination is wrapped inside a UnitDefinition, which provides for
 * assigning an identifier and optional name to the combination.  The
 * identifier can then be referenced from elsewhere in a model.  Thus, the
 * UnitDefinition class is the container, and Unit instances are placed
 * inside UnitDefinition instances.
 *
 * A Unit has four attributes named "kind", "exponent", "scale"
 * and "multiplier".  It represents a (possibly transformed) reference to a
 * base unit.  The attribute "kind" on Unit indicates the chosen base unit.
 * Its value must be one of the text strings listed below; this list
 * corresponds to SBML Level3:
 *
 * A few small differences exist between the Level3 list of base
 * units and the list defined in other Level/Version combinations of SBML.
 * Specifically, Levels of SBML before Level3 do not define
 * avogadro; conversely, Level2 Version1 defines Celsius,
 * and Level1 defines celsius, meter, and liter, none of
 * which are available in Level3.  In libSBML, each of the predefined
 * base unit names is represented by an enumeration value whose name begins with the characters
 * UNIT_KIND_, discussed in a separate section below.
 *
 * The attribute named "exponent" on Unit represents an exponent on the
 * unit.  In SBML Level2, the attribute is optional and has a default
 * value of 1 (one); in SBML Level3, the attribute is mandatory
 * and there is no default value.  A Unit also has an attribute
 * called "scale"; its value must be an integer exponent for a power-of-ten
 * multiplier used to set the scale of the unit.  For example, a unit
 * having a "kind" value of gram and a "scale" value of -3 signifies
 * 10<sup>-3</sup> * gram, or milligrams.  In SBML
 * Level2, the attribute is optional and has a default value of 0
 * (zero), because 10<sup> 0</sup> = 1; in SBML Level3, the attribute
 * is mandatory and has no default value.  Lastly, the attribute named
 * "multiplier" can be used to multiply the unit by a real-numbered factor;
 * this enables the definition of units that are not power-of-ten multiples
 * of SI units.  For instance, a multiplier of 0.3048 could be used to
 * define foot as a measure of length in terms of a metre.  The
 * "multiplier" attribute is optional in SBML Level2, where it has a
 * default value of 1 (one); in SBML Level3, the attribute is
 * mandatory and has no default value.
 *
 * # Unit identification codes
 *
 * As discussed above, SBML defines a set of base units which serves as the
 * starting point for new unit definitions.  This set of base units
 * consists of the SI units and a small number of additional convenience
 * units.
 *
 * Until SBML Level2 Version3, there
 * existed a data type in the SBML specifications called UnitKind,
 * enumerating the possible SBML base units.  Although SBML Level2
 * Version3 removed this type from the language specification,
 * libSBML maintains the corresponding enumeration type UnitKind_t as a
 * convenience and as a way to provide backward compatibility to previous
 * SBML Level/Version specifications.  (The removal in SBML Level2
 * Version3 of the enumeration UnitKind was also accompanied by
 * the redefinition of the data type UnitSId to include the previous
 * UnitKind values as reserved symbols in the UnitSId space.  This
 * change has no net effect on permissible models, their representation or
 * their syntax.  The purpose of the change in the SBML specification was
 * simply to clean up an inconsistency about the contexts in which these
 * values were usable.)
 *
 * As a consequence of the fact that libSBML supports models in all Levels
 * and Versions of SBML, libSBML's set of UNIT_KIND_ values is a union
 * of all the possible base unit names defined in the different SBML
 * specifications.  However, not every base unit is allowed in every
 * Level+Version combination of SBML.  Note in particular the following
 * exceptions:
 *
 * * The alternate spelling "meter" is included in
 * addition to the official SI spelling "metre".  This spelling is only
 * permitted in SBML Level1 models.
 *
 * * The alternate spelling "liter" is included in addition to the
 * official SI spelling "litre".  This spelling is only permitted in
 * SBML Level1 models.
 *
 * * The unit "Celsius" is included because of its presence in
 * specifications of SBML prior to SBML Level2 Version2.
 *
 * * The unit avogadro was introduced in SBML Level3, and
 * is only permitted for use in SBML Level3 models.
 *
 */
[Prefix="libsbml::"]
interface Unit {
  /**
   * Returns the "kind" of Unit this is.
   *
   * @return {UnitKind_t} the value of the "kind" attribute of this Unit as a
   * value from the UnitKind_t enumeration.
   */
  libsbml__idl__UnitKind_t getKind();

  /**
   * Sets the "kind" attribute value of this Unit.
   *
   * @param {UnitKind_t} kind a value from the UnitKind_t enumeration.
   */
  long setKind(libsbml__idl__UnitKind_t kind);

  /**
   * Predicate to test whether the "kind" attribute of this Unit is set.
   *
   * @return {boolean} true if the "kind" attribute of this Unit is set,
   * false otherwise.
   */
  boolean isSetKind();

  /**
   * Unsets the "kind" attribute value of this Unit.
   */
  long unsetKind();

  /**
   * Returns the value of the "scale" attribute of this unit.
   *
   * @return the "scale" value of this Unit, as an integer
   */
  long getScale();

  /**
   * Sets the "scale" attribute value of this Unit.
   *
   * @param {number} value the integer to which the attribute "scale" should be set
   */
  long setScale(long value);

  /**
   * Predicate to test whether the "scale" attribute of this Unit
   * is set.
   *
   * @return {boolean} true if the "scale" attribute of this Unit is set,
   * false otherwise
   */
  boolean isSetScale();

  /**
   * Sets the "multipler" attribute value of this Unit.
   *
   * @param {number} value the floating-point value to which the attribute
   * "multiplier" should be set
   */
  long setMultiplier(double value);

  /**
   * Predicate to test whether the "multiplier" attribute of this Unit
   * is set.
   *
   * @return {boolean} true if the "multiplier" attribute of this Unit is set,
   * false otherwise
   */
  boolean isSetMultiplier();

  /**
   * Unsets the "multipler" attribute value of this Unit.
   */
  long unsetMultiplier();

  /**
   * Initializes the fields of this Unit object to "typical" default
   * values.
   *
   * The SBML Unit component has slightly different aspects and default
   * attribute values in different SBML Levels and Versions.  This method
   * sets the values to certain common defaults, based mostly on what they
   * are in SBML Level 2.  Specifically:
   *
   * * Sets attribute "exponent" to 1
   * * Sets attribute "scale" to 0
   * * Sets attribute "multiplier" to 1.0
   *
   *
   * The "kind" attribute is left unchanged.
   */
  void initDefaults();

  /**
   * Returns the value of the "exponent" attribute of this unit.
   *
   * @return the "exponent" value of this Unit, as an integer
   */
  long getExponent();

  /**
   * Returns the value of the "exponent" attribute of this unit.
   *
   * @return the "exponent" value of this Unit, as a double
   */
  double getExponentAsDouble();

  /**
   * Sets the "exponent" attribute value of this Unit.
   *
   * @param {number} value the integer to which the attribute "exponent" should be set
   */
  long setExponent(double value);

  /**
   * Predicate to test whether the "exponent" attribute of this Unit
   * is set.
   *
   * @return {boolean} true if the "exponent" attribute of this Unit is set,
   * false otherwise
   */
  boolean isSetExponent();

  /**
   * Unsets the "exponent" attribute value of this Unit.
   */
  long unsetExponent ();

  /**
   * Returns the value of the "offset" attribute of this Unit.
   *
   * @return the "offset" value of this Unit, as a double
   */
  double getOffset();

  /**
   * Sets the "offset" attribute value of this Unit.
   *
   * @param {number} value the floating point value to which the attribute "offset"
   * should set
   */
  long setOffset(double value);

  /**
   * Unsets the "offset" attribute value of this Unit.
   */
  long unsetOffset();

  /**
   * Predicate to test whether a given string is the name of a built-in SBML
   * unit, depending on the SBML level, since new predefined units were added
   * between level 2 versions 1 and 2, and then all predefined units were removed
   * again in SBML Level 3.
   *
   * @param {string} name a string to be tested against the built-in unit names
   * @param {number} level the level of SBML one is checking
   *
   * @return {boolean} true if name is one of "substance", "volume",
   * or "time" and the level is 1; or if name is one of
   * "substance", "volume", "area", "length", or "time" and
   * the level is 2; false otherwise (including all values when
   * level is 3).
   *
   * @static
   */
  static boolean isBuiltIn(DOMString name, unsigned long level);

  /**
   * Predicate returning true if two
   * Unit objects are identical.
   *
   * Two Unit objects are considered to be identical if they match in
   * all attributes.  (Contrast this to the method areEquivalent(), which compares Unit objects only with respect
   * to certain attributes.)
   *
   * @param {Unit} unit1 the first Unit object to compare
   * @param {Unit} unit2 the second Unit object to compare
   *
   * @return {boolean} true if all the attributes of unit1 are identical
   * to the attributes of unit2, false otherwise
   *
   * @static
   */
  static boolean areIdentical(Unit unit1, Unit unit2);

  /**
   * Predicate returning true if
   * Unit objects are equivalent.
   *
   * Two Unit objects are considered to be equivalent either if (1) both
   * have a "kind" attribute value of dimensionless, or (2) their "kind",
   * "exponent" and (for SBML Level 2 Version 1) "offset"
   * attribute values are equal. (Contrast this to the method
   * areIdentical(), which compares Unit objects with respect to all
   * attributes, not just the "kind" and "exponent".)
   *
   * @param {Unit} unit1 the first Unit object to compare
   * @param {Unit} unit2 the second Unit object to compare
   *
   * @return {boolean} true if the "kind" and "exponent" attributes of unit1 are
   * identical to the kind and exponent attributes of unit2, or if the kind
   * attributes of both are dimensionless; false otherwise.
   *
   * @static
   */
  static boolean areEquivalent(Unit unit1, Unit unit2);

  /**
   * Manipulates the attributes of the Unit to express the unit with the
   * value of the scale attribute reduced to zero.
   *
   * For example, 1 millimetre can be expressed as a Unit with kind=
   * "metre" multiplier="1" scale="-3" exponent="1". It can also be
   * expressed as a Unit with kind="metre"
   * multiplier=<code>"0.001"</code> scale="0" exponent="1".
   *
   * @param {Unit} unit the Unit object to manipulate
   *
   * @static
   */
  static long removeScale(Unit unit);

  /**
   * Merges two Unit objects with the same "kind" attribute value into a
   * single Unit.
   *
   * For example, the following,
   * ```
   * <unit kind="metre" exponent="2"/>
   * <unit kind="metre" exponent="1"/>
   * ```
   * would be merged to become
   * ```
    *<unit kind="metre" exponent="3"/>
   * ```
   *
   * @param {Unit} unit1 the first Unit object; the result of the operation is
   * left as a new version of this unit, modified in-place - not modified if
   * the two units have different kinds
   *
   * @param {Unit} unit2 the second Unit object to merge with the first.
   *
   * @static
   */
  static void merge(Unit unit1, Unit unit2);

  boolean isAmpere();
  boolean isAvogadro();
  boolean isBecquerel();
  boolean isCandela();
  boolean isCelsius();
  boolean isCoulomb();
  boolean isDimensionless();
  boolean isFarad();
  boolean isGram();
  boolean isGray();
  boolean isHenry();
  boolean isHertz();
  boolean isItem();
  boolean isJoule();
  boolean isKatal();
  boolean isKelvin();
  boolean isKilogram();
  boolean isLitre();
  boolean isLumen();
  boolean isLux();
  boolean isMetre();
  boolean isMole();
  boolean isNewton();
  boolean isOhm();
  boolean isPascal();
  boolean isRadian();
  boolean isSecond();
  boolean isSiemens();
  boolean isSievert();
  boolean isSteradian();
  boolean isTesla();
  boolean isVolt();
  boolean isWatt();
  boolean isWeber();
};

Unit implements SBase;

/**
 * # A definition of a unit used in an SBML model.
 *
 * Units of measurement may be supplied in a number of contexts in an SBML
 * model.  The SBML unit definition facility uses two classes of objects,
 * UnitDefinition and Unit.  The approach to defining units in SBML is
 * compositional; for example, **meter second<sup> &ndash;2</sup>** is
 * constructed by combining a Unit object representing **meter** with
 * another Unit object representing **second<sup> &ndash;2</sup>**.
 * The combination is wrapped inside a UnitDefinition, which provides for
 * assigning an identifier and optional name to the combination.  The
 * identifier can then be referenced from elsewhere in a model.  Thus, the
 * UnitDefinition class is the container, and Unit instances are placed
 * inside UnitDefinition instances.
 *
 * Two points are worth discussing in the context of SBML units.  First,
 * unit declarations in SBML models are optional.  The consequence of
 * this is that a model must be numerically self-consistent independently
 * of unit declarations, for the benefit of software tools that cannot
 * interpret or manipulate units.  Unit declarations in SBML are thus more
 * akin to a type of annotation; they can indicate intentions, and can be
 * used by model readers for checking the consistency of the model,
 * labeling simulation output, etc., but any transformations of values
 * implied by different units must be incorporated explicitly into a
 * model.
 *
 * Second, the vast majority of situations that require new SBML unit
 * definitions involve simple multiplicative combinations of base units and
 * factors.  An example is **moles per litre per second**.  What
 * distinguishes these sorts of unit definitions from more complex ones is
 * that they may be expressed without the use of an additive offset from a
 * zero point.  The use of offsets complicates all unit definition systems,
 * yet in the domain of SBML, the real-life cases requiring offsets are few
 * (and in fact, to the best of our knowledge, only involve temperature).
 * Consequently, the SBML unit system has been consciously designed to
 * simplify implementation of unit support for the most common cases in
 * systems biology.  The cost of this simplification is to require units
 * with offsets to be handled explicitly by the modeler.
 *
 * ## Summary of the UnitDefinition construct
 *
 * UnitDefinition has two attributes and one subelement.  The two
 * attributes are "id" and "name", and the subelement is ListOfUnits.
 *
 * The required attribute "id" and optional attribute "name" are both
 * strings.  The "id" attribute is used to give the defined unit a unique
 * identifier by which other parts of an SBML model definition can refer to
 * it.  The "name" attribute is intended to be used for giving the unit
 * definition an optional human-readable name.  Please see the next section
 * for information about the values
 * permitted for "id".
 *
 * A UnitDefinition may contain exactly one ListOfUnits, and this list
 * may contain one or more Unit definitions; see the definitions of these
 * other object classes for more information about them.  In SBML
 * Level 2 and SBML Level 3 Version 1, if the ListOfUnits
 * was present, it must have one or more Unit definitions.  In SBML
 * Level 3 Version 2, this restriction was relaxed, and
 * a ListOfUnits was allowed to be empty.  In either case, if a
 * UnitDefinition had no child Unit elements, the unit was considered
 * to be undefined.
 *
 * The following
 * example illustrates a complete unit definition (when written in XML)
 * when all the pieces are combined together.  This defines "mmls"
 * to be millimoles per litre per second.
 *
 * ```
 * <listOfUnitDefinitions>
 *     <unitDefinition id="mmls">
 *         <listOfUnits>
 *             <unit kind="mole"   scale="-3"/>
 *             <unit kind="litre"  exponent="-1"/>
 *             <unit kind="second" exponent="-1"/>
 *         </listOfUnits>
 *     </unitDefinition>
 * </listOfUnitDefinitions>
 * ```
 *
 * ## Special considerations for Unit object identifiers
 *
 * The attribute "id" in UnitDefinition cannot be given simply any value,
 * and the precise details of the values permitted differ slightly between
 * Levels of SBML:
 *
 * * The "id" of a UnitDefinition must not contain a value from the
 * list of SBML's predefined base unit names (i.e., the strings gram,
 * litre, etc.).
 *
 * This list of predefined base units is nearly identical in SBML
 * Level 2 Version 4, the exception being that Level 2 does
 * not define avogadro.  SBML Level 2 Version 1 (and only
 * this Level+Version combination) provides an additional predefined unit
 * name, Celsius, not available in Level 3.  Finally, SBML
 * Level 1 Versions 2&ndash;3 provide two more additional
 * predefined unit names, meter and liter.  This is explained in
 * somewhat greater detail in the description of the Unit class.
 *
 *
 * * In SBML Level 2 (all Versions), there is an additional set of
 * reserved identifiers: substance, volume, area, length, and
 * time.  Using one of these values for the attribute "id" of a
 * UnitDefinition has the effect of redefining the model-wide default units
 * for the corresponding quantities.
 *
 * Also, SBML Level 2 imposes two limitations on redefining the
 * predefined unit substance, volume, area, length, and
 * time: (1) The UnitDefinition of a predefined SBML unit can only contain
 * a single Unit object within it.  (2) The value of the "kind" attribute
 * in a Unit instance must be drawn from one of the values in the second
 * column of the table above.
 *
 * The special unit names substance, volume, area, length, and
 * time are not defined by SBML Level 3, which uses a different
 * approach to setting model-wide inherited units.
 *
 *
 * ## Further comments about SBML's unit definition system
 *
 * The vast majority of modeling situations requiring new SBML unit
 * definitions involve simple multiplicative combinations of base units and
 * factors.  An example of this might be **moles per litre per
 * second**.  What distinguishes these sorts of simpler unit definitions
 * from more complex ones is that they may be expressed without the use of
 * an additive offset from a zero point.  The use of offsets complicates
 * all unit definition systems, yet in the domain of SBML the real-life
 * cases requiring offsets are few (and in fact, to the best of our
 * knowledge, only involve temperature).  Consequently, the SBML unit
 * system has been consciously designed in a way that attempts to simplify
 * implementation of unit support for the most common cases in systems
 * biology.
 *
 * As of SBML Level 2 Version 2, Unit no longer has the
 * attribute called "offset" introduced in SBML Level 2
 * Version 1.  It turned out that the general case involving units
 * with offsets was incorrectly defined, and few (if any) developers even
 * attempted to support offset-based units in their software.  In the
 * development of Level 2 Version 2, a consensus among SBML
 * developers emerged that a fully generalized unit scheme is so
 * confusing and complicated that it actually impedes interoperability.
 * SBML Level 2 Version 2, Version 3 and Version 4 acknowledge this
 * reality by reducing and simplifying the unit system, specifically by
 * removing the "offset" attribute on Unit and Celsius as a pre-defined
 * unit.
 *
 * The following guidelines suggest methods for handling units that do
 * require the use of zero offsets for their definitions:
 *
 * * **Handling Celsius**.  A model in which certain quantities are
 *   temperatures measured in degrees Celsius can be converted
 *   straightforwardly to a model in which those temperatures are in
 *   kelvin.  A software tool could do this by performing a straightforward
 *   substitution using the following relationship: **T<sub> kelvin</sub> =
 *   T<sub>Celsius</sub> + 273.15**.  In every mathematical formula of the
 *   model where a quantity (call it x) in degrees Celsius appears,
 *   replace x with **x<sub>k</sub>+ 273.15**, where
 *   **x<sub>k</sub>** is now in kelvin.  An alternative approach would
 *   be to use a FunctionDefinition object to define a function encapsulating this
 *   relationship above and then using that in the rest of the model as
 *   needed.  Since Celsius is a commonly-used unit, software tools could
 *   help users by providing users with the ability to express temperatures
 *   in Celsius in the tools' interfaces, and making substitutions
 *   automatically when writing out the SBML.
 *
 * * **Other units requiring offsets**.  One approach to handling
 *   other kinds of units is to use a FunctionDefinition to define a function
 *   encapsulating the necessary mathematical relationship, then
 *   substituting a call to this function wherever the original quantity
 *   appeared in the model.  For example, here is a possible definition for
 *   converting Fahrenheit to Celsius degrees:
 *
 * ```
 * <functionDefinition id="Fahrenheit_to_kelvin">
 *     <math xmlns="http://www.w3.org/1998/Math/MathML">
 *         <lambda>
 *             <bvar><ci> temp_in_fahrenheit </ci></bvar>
 *             <apply>
 *                 <divide/>
 *                 <apply>
 *                     <plus/>
 *                     <ci> temp_in_fahrenheit </ci>
 *                     <cn> 459.67 </cn>
 *                 </apply>
 *                 <cn> 1.8 </cn>
 *             </apply>
 *         </lambda>
 *     </math>
 * </functionDefinition>
 * ```
 *
 * * An alternative approach not requiring the use of function definitions
 *   is to use an AssignmentRule for each variable in Fahrenheit units.
 *   The AssignmentRule could compute the conversion from Fahrenheit to
 *   (say) kelvin, assign its value to a variable (in Kelvin units), and
 *   then that variable could be used elsewhere in the model.
 *
 * * Still another approach is to rewrite the mathematical formulas of a
 *   model to directly incorporate the conversion formula wherever the
 *   original quantity appeared.
 *
 *
 * Please consult the SBML specifications for more information about this
 * and other issues involving units.
 */
[Prefix="libsbml::"]
interface UnitDefinition {
  /**
   * Returns the number of Unit objects contained within this
   * UnitDefinition.
   *
   * @return an integer representing the number of Units in this UnitDefinition
   */
  unsigned long getNumUnits();

  /**
   * Creates a new and empty Unit, adds it to this UnitDefinition's list of
   * units, and returns it.
   *
   * @return {Unit} a newly constructed (and empty) Unit instance
   *
   * **Note:** It is worth emphasizing that the attribute "kind" value of a
   * Unit is a required attribute for a valid Unit definition.  The
   * createUnit() method does not assign a valid kind to the constructed
   * unit (instead, it sets the "kind" to UNIT_KIND_INVALID).
   * Callers are cautioned to set the newly-constructed Unit's kind using
   * Unit::setKind() soon after calling this method.
   */
  Unit createUnit();

  /**
   * Returns a specific Unit instance belonging to this UnitDefinition.
   *
   * @param {number} n an integer, the index of the Unit to be returned
   *
   * @return the nth Unit of this UnitDefinition; If the index n is invalid, NULL is returned
   */
  Unit getUnit(unsigned long n);
};

UnitDefinition implements SBase;

/**
 * # A helper class for getting UnitKind_t values
 *
 * Normally one would call the libSBML global function UnitKind_forName
 * to get the UnitKind_t value for a string, but global functions
 * are not available in this wrapper. Instead this helper class can be used.
 *
 * See the [libSBML C++ docs for UnitKind_forName](http://sbml.org/Software/libSBML/5.17.0/docs//cpp-api/_unit_kind_8c.html#aa8f09d91a2a76941730c23c5999cdd8d).
 *
 * @example
 * new libsbml.UnitKindConstructor().fromName('mole') // returns libsbml.UNIT_KIND_MOLE
 *
 */
[Prefix="libsbml::"]
interface UnitKindConstructor {
  void UnitKindConstructor();

  /**
   * Converts a text string naming a kind of unit to its corresponding
   * libSBML <code>UNIT_KIND_</code> constant/enumeration value.
   *
   * @param {string} name the name of a predefined base unit in SBML.
   *
   * @return {UnitKind_t} a value from UnitKind_t corresponding to the given
   * string name (determined in a case-insensitive manner).
   *
   * **Note:** For more information about the libSBML unit codes, please refer to
   * the class documentation for [Unit](http://sbml.org/Software/libSBML/5.17.0/docs//cpp-api/class_unit.html).
   */
  libsbml__idl__UnitKind_t fromName(ByteString name);
};
