/**
 * # Text-string SBML reader.
 *
 * The SBMLReader class provides the main interface for reading SBML content
 * from strings.  The methods for reading SBML all return an
 * SBMLDocument object representing the results.  In the case of failures
 * (such as if the SBML contains errors or a file cannot be read), the errors
 * will be recorded with the SBMLErrorLog object kept in the SBMLDocument
 * returned by SBMLReader.  Consequently, immediately after calling a method
 * on SBMLReader, callers should always check for errors and warnings using
 * the methods for this purpose provided by SBMLDocument.
 *
 * ## Support for reading compressed files
 *
 * The libsbml.js wrapper does not include library-level compression support.
 * Users who wish to utilize compressed models on the web should consider
 * [HTTP compression](https://developer.mozilla.org/en-US/docs/Web/HTTP/Compression).
 */
[Prefix="libsbml::"]
interface SBMLReader {
  /**
   * Creates a new SBMLReader object and returns it.
   *
   * The libSBML SBMLReader object offers methods for reading SBML in
   * XML form from files and text strings.
   */
  void SBMLReader();

  /**
   * Reads an SBML document from a text string.
   *
   * This method is flexible with respect to the presence of an XML
   * declaration at the beginning of the string.  In particular, if the
   * string in xml does not begin with the XML declaration
   * ```
   *  <?xml version='1.0' encoding='UTF-8'?>
   * ```
   * then this method will automatically prepend the declaration
   * to xml.
   *
   * This method will log a fatal error if the content given in the parameter
   * xml is not in SBML format.
   *
   * @param {string} xml a string containing a full SBML model
   *
   * @return {SBMLDocument} a pointer to the SBMLDocument created from the SBML content,
   * or a null pointer if xml is NULL.
   */
  SBMLDocument readSBMLFromString(DOMString sbmlstr);
};
