/**
 * # Base extension class for the package.
 *
 * This is the Distrib package extension of the SBMLExtension class that is
 * used to facilitate libSBML plug-ins in the implementation of an
 * SBMLLevel 3 package.
 */
[Prefix="libsbml::"]
interface DistribExtension {
  /**
   * Returns the XML namespace URI of the SBML Level 3 package implemented
   * by this libSBML extension.
   *
   * @return {string} the XML namespace, as a string.
   */
  static DOMString getXmlnsL3V1V1();
};
