/**
 * # DistribHypergeometricDistribution
 */
[Prefix="libsbml::"]
interface DistribHypergeometricDistribution {
  /**
   * Returns the value of the "numberOfSuccesses" element of this
   * DistribHypergeometricDistribution.
   *
   * @return {DistribUncertValue} the value of the "numberOfSuccesses" element of this
   * DistribHypergeometricDistribution as a DistribUncertValue.
   */
  DistribUncertValue getNumberOfSuccesses();


  /**
   * Returns the value of the "numberOfTrials" element of this
   * DistribHypergeometricDistribution.
   *
   * @return {DistribUncertValue} the value of the "numberOfTrials" element of this
   * DistribHypergeometricDistribution as a DistribUncertValue.
   */
  DistribUncertValue getNumberOfTrials();


  /**
   * Returns the value of the "populationSize" element of this
   * DistribHypergeometricDistribution.
   *
   * @return {DistribUncertValue} the value of the "populationSize" element of this
   * DistribHypergeometricDistribution as a DistribUncertValue.
   */
  DistribUncertValue getPopulationSize();


  /**
   * Predicate returning @c true if this DistribHypergeometricDistribution's
   * "numberOfSuccesses" element is set.
   *
   * @return {boolean} true if this DistribHypergeometricDistribution's
   * "numberOfSuccesses" element has been set, otherwise @c false is returned.
   */
  boolean isSetNumberOfSuccesses();


  /**
   * Predicate returning @c true if this DistribHypergeometricDistribution's
   * "numberOfTrials" element is set.
   *
   * @return {boolean} true if this DistribHypergeometricDistribution's
   * "numberOfTrials" element has been set, otherwise @c false is returned.
   */
  boolean isSetNumberOfTrials();


  /**
   * Predicate returning @c true if this DistribHypergeometricDistribution's
   * "populationSize" element is set.
   *
   * @return {boolean} true if this DistribHypergeometricDistribution's
   * "populationSize" element has been set, otherwise @c false is returned.
   */
  boolean isSetPopulationSize();


  /**
   * Sets the value of the "numberOfSuccesses" element of this
   * DistribHypergeometricDistribution.
   *
   * @param {DistribUncertValue} numberOfSuccesses DistribUncertValue value of the
   * "numberOfSuccesses" element to be set.
   */
  long setNumberOfSuccesses(DistribUncertValue numberOfSuccesses);


  /**
   * Sets the value of the "numberOfTrials" element of this
   * DistribHypergeometricDistribution.
   *
   * @param {DistribUncertValue} numberOfTrials DistribUncertValue value of the "numberOfTrials"
   * element to be set.
   */
  long setNumberOfTrials(DistribUncertValue numberOfTrials);


  /**
   * Sets the value of the "populationSize" element of this
   * DistribHypergeometricDistribution.
   *
   * @param {DistribUncertValue} populationSize DistribUncertValue value of the "populationSize"
   * element to be set.
   */
  long setPopulationSize(DistribUncertValue populationSize);


  /**
   * Creates a new DistribUncertValue object, adds it to this
   * DistribHypergeometricDistribution object and returns the
   * DistribUncertValue object created.
   *
   * @return {DistribUncertValue} a new DistribUncertValue object instance.
   */
  DistribUncertValue createNumberOfSuccesses();


  /**
   * Creates a new DistribUncertValue object, adds it to this
   * DistribHypergeometricDistribution object and returns the
   * DistribUncertValue object created.
   *
   * @return a new DistribUncertValue object instance.
   */
  DistribUncertValue createNumberOfTrials();


  /**
   * Creates a new DistribUncertValue object, adds it to this
   * DistribHypergeometricDistribution object and returns the
   * DistribUncertValue object created.
   *
   * @return {DistribUncertValue} a new DistribUncertValue object instance.
   */
  DistribUncertValue createPopulationSize();


  /**
   * Unsets the value of the "numberOfSuccesses" element of this
   * DistribHypergeometricDistribution.
   */
  long unsetNumberOfSuccesses();


  /**
   * Unsets the value of the "numberOfTrials" element of this
   * DistribHypergeometricDistribution.
   */
  long unsetNumberOfTrials();


  /**
   * Unsets the value of the "populationSize" element of this
   * DistribHypergeometricDistribution.
   */
  long unsetPopulationSize();
};

DistribHypergeometricDistribution implements DistribDiscreteUnivariateDistribution;
