/**
 * # DistribLogNormalDistribution
 */
[Prefix="libsbml::"]
interface DistribLogisticDistribution {
  /**
   * Returns the value of the "location" element of this
   * DistribLogisticDistribution.
   *
   * @return {DistribUncertValue} the value of the "location" element of this
   * DistribLogisticDistribution as a DistribUncertValue.
   */
  DistribUncertValue getLocation();


  /**
   * Returns the value of the "scale" element of this
   * DistribLogisticDistribution.
   *
   * @return {DistribUncertValue} the value of the "scale" element of this
   * DistribLogisticDistribution as a DistribUncertValue.
   */
  DistribUncertValue getScale();


  /**
   * Predicate returning true if this DistribLogisticDistribution's
   * "location" element is set.
   *
   * @return {boolean} true if this DistribLogisticDistribution's "location" element
   * has been set, otherwise false is returned.
   */
  boolean isSetLocation();


  /**
   * Predicate returning true if this DistribLogisticDistribution's "scale"
   * element is set.
   *
   * @return {boolean} true if this DistribLogisticDistribution's "scale" element has
   * been set, otherwise false is returned.
   */
  boolean isSetScale();


  /**
   * Sets the value of the "location" element of this
   * DistribLogisticDistribution.
   *
   * @param {DistribUncertValue} location DistribUncertValue value of the "location" element to be
   * set.
   */
  long setLocation(DistribUncertValue location);


  /**
   * Sets the value of the "scale" element of this DistribLogisticDistribution.
   *
   * @param {DistribUncertValue} scale DistribUncertValue value of the "scale" element to be set.
   */
  long setScale(DistribUncertValue scale);


  /**
   * Creates a new DistribUncertValue object, adds it to this
   * DistribLogisticDistribution object and returns the DistribUncertValue
   * object created.
   *
   * @return {DistribUncertValue} a new DistribUncertValue object instance.
   */
  DistribUncertValue createLocation();


  /**
   * Creates a new DistribUncertValue object, adds it to this
   * DistribLogisticDistribution object and returns the DistribUncertValue
   * object created.
   *
   * @return {} a new DistribUncertValue object instance.
   */
  DistribUncertValue createScale();


  /**
   * Unsets the value of the "location" element of this
   * DistribLogisticDistribution.
   */
  long unsetLocation();


  /**
   * Unsets the value of the "scale" element of this
   * DistribLogisticDistribution.
   */
  long unsetScale();
};

DistribLogNormalDistribution implements DistribContinuousUnivariateDistribution;
