/**
 * # DistribPoissonDistribution
 */
[Prefix="libsbml::"]
interface DistribPoissonDistribution {
  /**
   * Creates a new DistribPoissonDistribution using the given SBML Level,
   * Version and "distrib" package version.
   *
   * @param {number} level an unsigned int, the SBML Level to assign to this
   * DistribUncertStatisticSpan.
   *
   * @param {number} version an unsigned int, the SBML Version to assign to this
   * DistribUncertStatisticSpan.
   *
   * @param {number} pkgVersion an unsigned int, the SBML Distrib Version to assign to
   * this DistribUncertStatisticSpan.
   */
  void DistribPoissonDistribution(unsigned long level, unsigned long version, unsigned long pkgVersion);

  /**
   * Returns the value of the "rate" element of this
   * DistribPoissonDistribution.
   *
   * @return {DistribUncertValue} the value of the "rate" element of this DistribPoissonDistribution
   * as a DistribUncertValue.
   */
  DistribUncertValue getRate();


  /**
   * Predicate returning true if this DistribPoissonDistribution's "rate"
   * element is set.
   *
   * @return {boolean} true if this DistribPoissonDistribution's "rate" element has
   * been set, otherwise false is returned.
   */
  boolean isSetRate();


  /**
   * Sets the value of the "rate" element of this DistribPoissonDistribution.
   *
   * @param {DistribUncertValue} rate DistribUncertValue value of the "rate" element to be set.
   */
  long setRate(DistribUncertValue rate);


  /**
   * Creates a new DistribUncertValue object, adds it to this
   * DistribPoissonDistribution object and returns the DistribUncertValue
   * object created.
   *
   * @return {DistribUncertValue} a new DistribUncertValue object instance.
   */
  DistribUncertValue createRate();


  /**
   * Unsets the value of the "rate" element of this DistribPoissonDistribution.
   */
  long unsetRate();
};

DistribPoissonDistribution implements DistribDiscreteUnivariateDistribution;
