/**
 * # DistribWeibullDistribution
 */
[Prefix="libsbml::"]
interface DistribWeibullDistribution {
  /**
   * Creates a new DistribWeibullDistribution using the given SBML Level,
   * Version and "distrib" package version.
   *
   * @param {number} level an unsigned int, the SBML Level to assign to this
   * DistribUncertStatisticSpan.
   *
   * @param {number} version an unsigned int, the SBML Version to assign to this
   * DistribUncertStatisticSpan.
   *
   * @param {number} pkgVersion an unsigned int, the SBML Distrib Version to assign to
   * this DistribUncertStatisticSpan.
   */
  void DistribWeibullDistribution(unsigned long level, unsigned long version, unsigned long pkgVersion);

  /**
   * Returns the value of the "scale" element of this
   * DistribWeibullDistribution.
   *
   * @return {DistribUncertValue} the value of the "scale" element of this
   * DistribWeibullDistribution as a DistribUncertValue.
   */
  DistribUncertValue getScale();


  /**
   * Returns the value of the "shape" element of this
   * DistribWeibullDistribution.
   *
   * @return {DistribUncertValue} the value of the "shape" element of this
   * DistribWeibullDistribution as a DistribUncertValue.
   */
  DistribUncertValue getShape();


  /**
   * Predicate returning @c true if this DistribWeibullDistribution's "scale"
   * element is set.
   *
   * @return {boolean} true if this DistribWeibullDistribution's "scale" element has
   * been set, otherwise @c false is returned.
   */
  boolean isSetScale();


  /**
   * Predicate returning @c true if this DistribWeibullDistribution's "shape"
   * element is set.
   *
   * @return {boolean} true if this DistribWeibullDistribution's "shape" element has
   * been set, otherwise @c false is returned.
   */
  boolean isSetShape();


  /**
   * Sets the value of the "scale" element of this DistribWeibullDistribution.
   *
   * @param {DistribUncertValue} scale DistribUncertValue value of the "scale" element to be set.
   */
  long setScale(DistribUncertValue scale);


  /**
   * Sets the value of the "shape" element of this DistribWeibullDistribution.
   *
   * @param {DistribUncertValue} shape DistribUncertValue value of the "shape" element to be set.
   */
  long setShape(DistribUncertValue shape);


  /**
   * Creates a new DistribUncertValue object, adds it to this
   * DistribWeibullDistribution object and returns the DistribUncertValue
   * object created.
   *
   * @return {DistribUncertValue} a new DistribUncertValue object instance.
   */
  DistribUncertValue createScale();


  /**
   * Creates a new DistribUncertValue object, adds it to this
   * DistribWeibullDistribution object and returns the DistribUncertValue
   * object created.
   *
   * @return {DistribUncertValue} a new DistribUncertValue object instance.
   */
  DistribUncertValue createShape();


  /**
   * Unsets the value of the "scale" element of this
   * DistribWeibullDistribution.
   */
  long unsetScale();


  /**
   * Unsets the value of the "shape" element of this
   * DistribWeibullDistribution.
   */
  long unsetShape();
};

DistribWeibullDistribution implements DistribContinuousUnivariateDistribution;
