/**
 * # Spatial dimensions of a 2D or 3D shape.
 *
 * A dimension is specified via the required attributes width, height, and an
 * optional attribute depth, all of which are of type double. If the
 * attribute depth is not specified, the object is a two dimensional object.
 * The width attribute of Dimensions specifies the size of the object in the
 * direction of the positive x axis, the height attribute specifies the size
 * of the object along the positive y axis and the depth attribute specifies
 * the size of the object along the positive z axis. All sizes for Dimensions
 * objects are positive values, and so the attributes are not allowed to take
 * negative values.  The Dimensions class also has an optional attribute id
 * of type SId. While not used in the &ldquo;layout&rdquo; package, it can be
 * used by programs to refer to the elements.
 */
[Prefix="libsbml::"]
interface Dimensions {
  /**
   * Creates a new Dimensions object with the given sizes.
   *
   * @param {LayoutPkgNamespaces} the namespace
   * @param {number} w width
   * @param {number} h height
   * @param {number} d depth
   */
  void Dimensions(LayoutPkgNamespaces ns, double w, double h, double d);

  /**
   * Sets the width to the given value.
   *
   * @param {number} w the width to use
   */
  void setWidth(double val);

  /**
   * Sets the height to the given value.
   *
   * @param h {number} the height to use
   */
  void setHeight(double val);

  /**
   * Sets the depth to the given value.  This will set
   * the depth to be 'explicitly set'.
   *
   * @param {number} d the depth to use
   */
  void setDepth(double val);

  /**
   * Returns the width.
   *
   * @return {number} the width attribute as a double.
   */
  double getWidth();

  /**
   * Returns the height.
   *
   * @return {number} the height attribute as a double.
   */
  double getHeight();

  /**
   * Returns the depth.
   *
   * @return {number} the depth attribute as a double.
   */
  double getDepth();
};

Dimensions implements SBase;

/**
 * # Representation of a point.
 *
 * A point is specified via the required attributes 'x', 'y' and an optional
 * attribute 'z', all of which are of type double. If the attribute z is not
 * specified, the object is a two dimensional object.  The Point class also
 * has an optional attribute id of type SId. While not used in the
 * "layout" package, it can be used by programs to refer to the
 * elements.
 */
[Prefix="libsbml::"]
interface Point {
  /**
   * Sets the x offset.
   *
   * @param {number} x
   */
  void setX(double x);

  /**
   * Sets the y offset.
   *
   * @param {number} y
   */
  void setY(double y);

  /**
   * Sets the z offset.
   *
   * @param {number} z
   */
  void setZ(double z);

  /**
   * Sets the x offset.
   *
   * @param {number} x
   */
  void setXOffset(double x);

  /**
   * Sets the y offset.
   *
   * @param {number} y
   */
  void setYOffset(double y);

  /**
   * Sets the z offset.
   *
   * @param {number} y
   */
  void setZOffset(double z);

  /**
   * Returns the x offset.
   *
   * @return {number}
   */
  double x();

  /**
   * Returns the y offset.
   *
   * @return {number}
   */
  double y();

  /**
   * Returns the z offset.
   *
   * @return {number}
   */
  double z();

  /**
   * Returns the x offset.
   *
   * @return {number}
   */
  double getXOffset();

  /**
   * Returns the y offset.
   *
   * @return {number}
   */
  double getYOffset();

  /**
   * Returns the z offset.
   *
   * @return {number}
   */
  double getZOffset();
};

Point implements SBase;

/**
 * # A bounding box for an item in a diagram.
 */
[Prefix="libsbml::"]
interface BoundingBox {
  /**
   * Returns the dimensions of the BoundingBox as const reference to a
   * Dimensions object.
   *
   * @return the Dimensions representing the dimensions.
   */
  Dimensions getDimensions();

  /**
   * Sets the dimensions to a copy of the Dimensions object given.
   *
   * @param {Dimensions} d the Dimensions to use
   */
  void setDimensions(Dimensions b);

  /**
   * Returns the position of the BoundingBox as const reference to a Point
   * object.
   *
   * @return {Point} the Point representing the position.
   */
  Point getPosition();

  /**
   * Sets the position to a copy of the Point object given.
   *
   * @param {Point} p the Point to use as the position
   */
  void setPosition(Point b);

  /**
   * Set x offset of the bounding box.
   *
   * @param {number} x the double value to set the x offset to
   */
  void setX(double x);

  /**
   * Set y offset of the bounding box.
   *
   * @param {number} y the double value to set the y offset to
   */
  void setY(double y);

  /**
   * Set z offset of the bounding box.
   *
   * @param {number} z the double value to set the z offset to
   */
  void setZ(double z);

  /**
   * Get the x offset of the bounding box.
   *
   * @return {number} the double value of the x offset.
   */
  double x();

  /**
   * Get the y offset of the bounding box.
   *
   * @return {number} the double value of the y offset.
   */
  double y();

  /**
   * Get the z offset of the bounding box.
   *
   * @return {number} the double value of the z offset.
   */
  double z();
};

BoundingBox implements SBase;

/**
 * # Base class of objects that store layouts.
 *
 * All the more specific layout elements (CompartmentGlyph, GeneralGlyph,
 * SpeciesGlyph, ReactionGlyph, ReferenceGlyph, TextGlyph, and
 * SpeciesReferenceGlyph) are derived from the class GraphicalObject. Each
 * object of class GraphicalObject has a mandatory BoundingBox, which
 * specifies the position and the size of the object.  While GraphicalObject
 * is the base class for most elements in the &ldquo;layout&rdquo; package,
 * it is not an abstract class. It can be instantiated when used in the
 * listOfAdditionalGraphicalObjects to describe additional elements and
 * relationships. Since it only describes a BoundingBox, programs are
 * encouraged to add Annotation objects that describe program-specific
 * graphical information.
 */
[Prefix="libsbml::"]
interface GraphicalObject {
};

GraphicalObject implements SBase;

/**
 * # A glyph for an SBML compartment.
 */
[Prefix="libsbml::"]
interface CompartmentGlyph {
};

CompartmentGlyph implements SBase;

/**
 * # A glyph for miscellaneous items.
 *
 * The GeneralGlyph is used to facilitate the representation of elements
 * other than Compartment, Species and Reaction and thus can be used for the
 * display of relationships of Rule or elements defined by other SBML
 * packages. It closely follows the structure of the ReactionGlyph.
 * GeneralGlyph is defined to have an optional attribute reference as well as
 * the elements curve, listOfReferenceGlyphs and listOfSubGlyphs.
 */
[Prefix="libsbml::"]
interface GeneralGlyph {
};

GeneralGlyph implements SBase;

/**
 * # A glyph for an SBML reaction.
 *
 * Analogous to how a Reaction object has to at least have one reactant or
 * product, the ReactionGlyph has to at least have one SpeciesReferenceGlyph
 * stored in the ListOfSpeciesReferenceGlyphs. Figure 12 on the following
 * page provides the UML diagram for the class definition.  The ReactionGlyph
 * inherits from GraphicalObject. In addition to the attributes inherited
 * from GraphicalObject, the ReactionGlyph is described by an attribute
 * reaction, a Curve element and a listOfSpeciesReferenceGlyphs element.  The
 * Curve describes the center section of a ReactionGlyph. The center section
 * is frequently used by tools to separate the point where substrates arcs
 * come together, from the point where product arcs split off. The Curve is
 * optional, and when not present the dimensions of the inherited BoundingBox
 * describes the center section, by storing its position and dimension.
 */
[Prefix="libsbml::"]
interface ReactionGlyph {
  /**
   * Returns the id of the associated reaction.
   *
   * @return {string}
   */
  DOMString getReactionId();

  /**
   * Sets the id of the associated reaction.
   *
   * @param {string} id
   */
  long setReactionId(DOMString id);

  /**
   * Returns {boolean} true if the id of the associated reaction is not the empty
   * string.
   */
  boolean isSetReactionId();

  BoundingBox getBoundingBox();
  void setBoundingBox(BoundingBox b);

  /**
   * Returns the number of species reference glyph objects.
   */
  unsigned long getNumSpeciesReferenceGlyphs();

  /**
   * Returns the species reference glyph with the given @p index.
   * If the index is invalid, @c NULL is returned.
   *
   * @return {SpeciesReferenceGlyph}
   */
  SpeciesReferenceGlyph getSpeciesReferenceGlyph(unsigned long n);

  /**
   * Creates a new SpeciesReferenceGlyph object, adds it to the end of the
   * list of species reference objects and returns a reference to the newly
   * created object.
   *
   * @return {SpeciesReferenceGlyph}
   */
  SpeciesReferenceGlyph createSpeciesReferenceGlyph();

  /**
   * Creates a new LineSegment object, adds it to the end of the list of
   * curve segment objects of the curve and returns a reference to the
   * newly created object.
   *
   * @return {LineSegment}
   */
  LineSegment createLineSegment();

  /**
   * Creates a new CubicBezier object, adds it to the end of the list of
   * curve segment objects of the curve and returns a reference to the
   * newly created object.
   *
   * @return {CubicBezier}
   */
   CubicBezier createCubicBezier();
};

ReactionGlyph implements SBase;

/**
 * # A glyph for an SBML species.
 *
 * In addition to the attributes it inherits from GraphicalObject, the
 * SpeciesGlyph object has an optional 'species' attribute.
 */
[Prefix="libsbml::"]
interface SpeciesGlyph {
  BoundingBox getBoundingBox();
  void setBoundingBox(BoundingBox b);

  /**
   * Returns the id of the associated species object.
   *
   * @return {string}
   */
  DOMString getSpeciesId();

  /**
   * Sets the id of the associated species object.
   *
   * @param {string} id
   */
  void setSpeciesId(DOMString id);

  /**
   * Returns true if the id of the associated species object is not the
   * empty string.
   *
   * @return {boolean}
   */
  boolean isSetSpeciesId();
};

SpeciesGlyph implements SBase;

/**
 * # A glyph for an SBML <em>species reference</em>.
 *
 * The SpeciesReferenceGlyph element describes the graphical connection
 * between a SpeciesGlyph and a ReactionGlyph (which would be an arrow or
 * some curve in most cases). A SpeciesReferenceGlyph inherits from
 * GraphicalObject, and adds a mandatory attribute 'speciesGlyph' and two
 * optional attributes 'speciesReference' and 'role'. Optionally, the
 * SpeciesReferenceGlyph also has a child element 'curve'.
 *
 * If the curve is specified, it overrides the inherited bounding box.
 */
[Prefix="libsbml::"]
interface SpeciesReferenceGlyph {
  BoundingBox getBoundingBox();
  void setBoundingBox(BoundingBox b);

  /**
   * Creates a new CubicBezier object, adds it to the end of the list of
   * curve segment objects of the curve and returns a reference to the
   * newly created object.
   *
   * @return {CubicBezier}
   */
  CubicBezier createCubicBezier();

  /**
   * Creates a new LineSegment object, adds it to the end of the list of
   * curve segment objects of the curve and returns a reference to the
   * newly created object.
   *
   * @return {LineSegment}
   */
  LineSegment createLineSegment();

  /**
   * Returns the curve object for the species reference glyph
   *
   * @return {Curve}
   */
  Curve getCurve();

  /**
   * Returns true if the curve consists of one or more segments.
   *
   * @return {boolean}
   */
  boolean isSetCurve();
};

SpeciesReferenceGlyph implements SBase;

/**
 * # A glyph for a text label.
 *
 * The TextGlyph class describes the position and dimension of text labels
 * in the &ldquo;layout&rdquo; package.  It inherits from GraphicalObject and
 * adds the attributes graphicalObject, text and originOfText.
 */
[Prefix="libsbml::"]
interface TextGlyph {
  BoundingBox getBoundingBox();
  void setBoundingBox(BoundingBox b);

  DOMString getText();
  void setText(DOMString t);
  boolean isSetText();
};

TextGlyph implements SBase;

[Prefix="libsbml::"]
interface ListOfLayouts {
  SBasePlugin getPlugin(DOMString name);
};

/**
 * Plugin subclass for the layout extension.
 */
[Prefix="libsbml::"]
interface LayoutModelPlugin {
  /**
   * Creates a new layout object and adds it to the list of layout objects
   * and returns it.
   *
   * @return {Layout} a new layout object
   */
  Layout createLayout();

  // NOTE: libSBML signedness is inconsistent here
  /**
   * Returns the number of layout objects.
   *
   * @return {number} the number of layout objects.
   */
  long getNumLayouts();

  /**
   * Returns the layout object that belongs to the given index. If the
   * index is invalid, @c NULL is returned.
   *
   * @param {number} index the index of list of layout objects
   *
   * @return {Layout} the Layout object that belongs to the given index. NULL
   * is returned if the index is invalid.
   */
  Layout getLayout(unsigned long n);

  /**
   * Returns the ListOfLayouts object for this Model.
   *
   * @return {ListOfLayouts} the ListOfLayouts object for this Model.
   */
  ListOfLayouts getListOfLayouts();
};

[Prefix="libsbml::"]
interface LayoutPkgNamespaces {
  void LayoutPkgNamespaces(unsigned long level, unsigned long version);
};

[Prefix="libsbmljs::"]
interface LayoutCaster {
  void LayoutCaster();
  LayoutModelPlugin castToLayoutPlugin(SBasePlugin p);
};

/**
 * The layout extension.
 */
[Prefix="libsbml::"]
interface LayoutExtension {
};

[Prefix="libsbmljs::"]
interface LayoutExtensionWrapper {
  void LayoutExtensionWrapper();
  DOMString getXmlnsL2();
  DOMString getXmlnsL3V1V1();
};

[Prefix="libsbmljs::"]
interface CurveCaster {
  void CurveCaster();
  boolean isCubicBezier(LineSegment x);
  CubicBezier castToCubicBezier(LineSegment x);
};
