/**
 * The SBML Arrays Index class.
 * @type {String}
 */
[Prefix="libsbml::"]
interface Index {
  /**
   * Returns the value of the "referencedAttribute" attribute of this Index.
   *
   * @return {string} the value of the "referencedAttribute" attribute of this Index as
   * a string.
   */
  DOMString getReferencedAttribute();


  /**
   * Returns the value of the "arrayDimension" attribute of this Index.
   *
   * @return {number} the value of the "arrayDimension" attribute of this Index as a
   * unsigned integer.
   */
  unsigned long getArrayDimension();


  /**
   * Predicate returning true if this Index's "referencedAttribute"
   * attribute is set.
   *
   * @return {boolean} true if this Index's "referencedAttribute" attribute has been
   * set, otherwise false is returned.
   */
  boolean isSetReferencedAttribute();


  /**
   * Predicate returning true if this Index's "arrayDimension" attribute is
   * set.
   *
   * @return {boolean} true if this Index's "arrayDimension" attribute has been set,
   * otherwise false is returned.
   */
  boolean isSetArrayDimension();


  /**
   * Sets the value of the "referencedAttribute" attribute of this Index.
   *
   * @param {string} referencedAttribute std::string& value of the "referencedAttribute"
   * attribute to be set.
   */
  long setReferencedAttribute(DOMString referencedAttribute);


  /**
   * Sets the value of the "arrayDimension" attribute of this Index.
   *
   * @param {number} arrayDimension unsigned long value of the "arrayDimension" attribute
   * to be set.
   */
  long setArrayDimension(unsigned long arrayDimension);


  /**
   * Unsets the value of the "referencedAttribute" attribute of this Index.
   */
  long unsetReferencedAttribute();


  /**
   * Unsets the value of the "arrayDimension" attribute of this Index.
   */
  long unsetArrayDimension();


  /**
   * Returns the value of the "math" element of this Index.
   *
   * @return the value of the "math" element of this Index as a ASTNode.
   */
  ASTNode getMath();


  /**
   * Predicate returning true if this Index's "math" element is set.
   *
   * @return {boolean} true if this Index's "math" element has been set, otherwise @c
   * false is returned.
   */
  boolean isSetMath();


  /**
   * Sets the value of the "math" element of this Index.
   *
   * @param {ASTNode} math value of the "math" element to be set.
   */
  long setMath(ASTNode math);


  /**
   * Unsets the value of the "math" element of this Index.
   */
  long unsetMath();
};

Index implements SBase;
