/**
 * # Base extension class for the "fbc" package.
 *
 * There are currently two possible namespaces defined for the Flux Balance
 * Constraints package:
 * "http://www.sbml.org/sbml/level3/version1/fbc/version1" and
 * "http://www.sbml.org/sbml/level3/version1/fbc/version2".  Despite both
 * referencing SBML Level 3 Version 1 explicitly, both versions of
 * this package (and all such packages) can be used without change in SBML
 * Level 3 Version 2 documents.  The only caveat is that features of
 * the SBML Level 3 Version 2 specification that were not present in
 * Level 1 may not be used by constructs from the Flux Balance Constraints
 * package.
 */
[Prefix="libsbml::"]
interface FbcExtension {
  /**
   * Returns the XML namespace URI of the SBML Level 3 package
   * implemented by this libSBML extension.
   *
   * @return {string} the XML namespace as a string.
   */
  static DOMString getXmlnsL3V1V1();

  /**
   * Returns the XML namespace URI of the SBML Level 3 package
   * implemented by this libSBML extension.
   *
   * @return {string} the XML namespace as a string.
   */
  static DOMString getXmlnsL3V1V2();
};
